# version: "3.9"

networks:
  fb98_network:
    driver: bridge
  proxy:
    external: true

services:
#front-end
  fb98-client:
    container_name: ui.client
    image: bkhang1227/fb98.ui:client
    depends_on: [fb98.bootstrapper]
    networks: [fb98_network, proxy]

  fb98-admin:
    container_name: ui.admin
    image: bkhang1227/fb98.ui:admin
    depends_on: [fb98.bootstrapper]
    networks: [fb98_network, proxy]

#back-end
  fb98.bootstrapper:
    container_name: bootstrapper
    image: bkhang1227/fb98:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production  
      - Redis__ConnectionString=redis:6379,password=your_secure_password,abortConnect=false,connectTimeout=1000
      - ConnectionStrings__RabbitMq=amqp://myuser:mypassword@rabbitmq:5672/
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=fb98db;Username=postgres;Password=yourpassword
    depends_on:
      - db
      - rabbitmq
      - redis
    networks: 
      - fb98_network 
      - proxy
    volumes:
      - app_data:/app/data

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: fb98db
    networks:
      - fb98_network
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    networks:
      - fb98_network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    healthcheck:
        test: ["CMD", "rabbitmqctl", "status"]
        interval: 10s
        timeout: 5s
        retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
      RABBITMQ_DEFAULT_VHOST: vhost
    networks:
      - fb98_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - fb98_network
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=your_secure_password
    command: ["redis-server", "--requirepass", "your_secure_password", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  rabbitmq_data:
  rabbitmq_logs:
  redis_data:
  app_data:
  db_data: