<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>b6d9ec4d-aef5-4355-b6e7-a05b4d7230da</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <DockerfileContext>..\..\..</DockerfileContext>
        <DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
        <Configurations>Debug;Release;IdentityModule;CatalogModule</Configurations>
    </PropertyGroup>

    <ItemGroup>
        <Content Remove="SeedData\CategorySeed.json" />
        <Content Remove="SeedData\ProductSeed.json" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.AspNetCoreServer.Hosting" Version="1.7.4" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Modules\Catalog\FB98.Modules.Catalog.Api\FB98.Modules.Catalog.Api.csproj" />
        <ProjectReference Include="..\..\Modules\Cinemas\FB98.Modules.Cinemas.Api\FB98.Modules.Cinemas.Api.csproj" />
        <ProjectReference Include="..\..\Modules\Customers\FB98.Modules.Customers.Api\FB98.Modules.Customers.Api.csproj" />
        <ProjectReference Include="..\..\Modules\Identity\FB98.Modules.Identity.Api\FB98.Modules.Identity.Api.csproj" />
        <ProjectReference Include="..\..\Modules\Movies\FB98.Modules.Movies.Api\FB98.Modules.Movies.Api.csproj" />
        <ProjectReference Include="..\..\Modules\Orders\FB98.Modules.Orders.Api\FB98.Modules.Orders.Api.csproj" />
        <ProjectReference Include="..\..\Modules\Payments\FB98.Modules.Payments.Api\FB98.Modules.Payments.Api.csproj" />
        <ProjectReference Include="..\..\Modules\Shows\FB98.Modules.Shows.Api\FB98.Modules.Shows.Api.csproj" />
        <ProjectReference Include="..\..\Modules\Systems\FB98.Modules.Systems.Api\FB98.Modules.Systems.Api.csproj" />
        <ProjectReference Include="..\..\Modules\Tickets\FB98.Modules.Tickets.Api\FB98.Modules.Tickets.Api.csproj" />
        <ProjectReference Include="..\..\Modules\Warehouse\FB98.Modules.Warehouse.Api\FB98.Modules.Warehouse.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="SeedData\Orders\" />
        <Folder Include="SeedData\Warehouse\" />
    </ItemGroup>

    <ItemGroup>
        <None Include="SeedData\Catalog\CategorySeed.json" />
        <None Include="SeedData\Catalog\ProductSeed.json" />
    </ItemGroup>

    <ProjectExtensions>
        <VisualStudio>
            <UserProperties />
        </VisualStudio>
    </ProjectExtensions>

</Project>