<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;CatalogModule</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Identity\FB98.Modules.Identity.Domain\FB98.Modules.Identity.Domain.csproj" />
  </ItemGroup>

</Project>
